### ISSUE TITLE
Feature Request: Trailer MPA Rating

### ISSUE THREAD

**Issue by mLgz0rn** [CherryFloors/jellyfin-plugin-cinemamode#5]
Hey! first of all, thank you very much for this plugin, it works really well.
Alot better than the intros plugin.

Would it be possible to make it so a trailer for lets say an R rated movie does not play when watching a G rated movie?

Don't know how complicated this would be.

Maybe something like this.

Movie: G = Trailer: G
Movie: PG = Trailer: PG, G
Movie: PG-13 = Trailer: PG-13, PG, G
Movie: R = Trailer: R, PG-13, PG, G
Movie: NC-17 = Trailer: R, PG-13, PG, G

**Comment by CherryFloors** [comment]
Happy you're using it. This is something I planned to implement and is part of the reason I haven't made a post about this plugin in any of the forums/discussions. I wanted to run it on my server for a while to make sure it was stable, using channels is a bit of a hack. But since you discovered the repo I guess its time. I really want to keep the config to a minimum for now so I'll add a check box to enforce rating parity that's enabled by default. I'll pick this up when I get some spare time.

I'll not that the plugin does select trailers based on the user, so in the mean time it wont show trailers for movies that the user doesn't have access to. But an R rated trailer before a G rated movie could be a buzzkill for anyone.

**Comment by mLgz0rn** [comment]
I actually found it in a reddit thread while looking for something else https://www.reddit.com/r/jellyfin/comments/13naewh/list_of_known_jellyfin_plugin_repos_2023_update/ so it's definitely out there 😅.

Sound great!
Maybe a combination of Ratings and Genres?
More because i guess every country has their own ratings, and some movies jellyfin doesn't even find ratings for, then it could fall back to genres.

**Comment by CherryFloors** [comment]
The feature has been added. For now, any content without a rating will be ignored (This in not the same as an "NR" rating). If the plugin cant verify a rating level or there are no results satisfying the rating level, no trailer is played.

Falling back to genre may be functionality that is added in the future. I have added a discussions page to the repo, feel free to put thoughts or ideas there. Thanks for providing feedback and beta testing.
